/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\B-Projects\\9-vuePress-Doc\\SwIoT-Doc\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-5edeba8e",
    path: "/about/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5edeba8e").then(next)
    },
  },
  {
    path: "/about/index.html",
    redirect: "/about/"
  },
  {
    name: "v-0a7ee641",
    path: "/documentation/bigScreen/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0a7ee641").then(next)
    },
  },
  {
    path: "/documentation/bigScreen/index.html",
    redirect: "/documentation/bigScreen/"
  },
  {
    name: "v-3b2ca959",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3b2ca959").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-17487942",
    path: "/documentation/congfiguration/%E5%88%9B%E5%BB%BA%E8%87%AA%E5%AE%9A%E4%B9%89g2Plots%E7%BB%84%E4%BB%B6/1.1%E5%88%9B%E5%BB%BA%E7%9B%AE%E5%BD%95/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-17487942").then(next)
    },
  },
  {
    path: "/documentation/congfiguration/创建自定义g2Plots组件/1.1创建目录/",
    redirect: "/documentation/congfiguration/%E5%88%9B%E5%BB%BA%E8%87%AA%E5%AE%9A%E4%B9%89g2Plots%E7%BB%84%E4%BB%B6/1.1%E5%88%9B%E5%BB%BA%E7%9B%AE%E5%BD%95/"
  },
  {
    path: "/documentation/congfiguration/%E5%88%9B%E5%BB%BA%E8%87%AA%E5%AE%9A%E4%B9%89g2Plots%E7%BB%84%E4%BB%B6/1.1%E5%88%9B%E5%BB%BA%E7%9B%AE%E5%BD%95/index.html",
    redirect: "/documentation/congfiguration/%E5%88%9B%E5%BB%BA%E8%87%AA%E5%AE%9A%E4%B9%89g2Plots%E7%BB%84%E4%BB%B6/1.1%E5%88%9B%E5%BB%BA%E7%9B%AE%E5%BD%95/"
  },
  {
    path: "/documentation/congfiguration/创建自定义g2Plots组件/1.1创建目录/",
    redirect: "/documentation/congfiguration/%E5%88%9B%E5%BB%BA%E8%87%AA%E5%AE%9A%E4%B9%89g2Plots%E7%BB%84%E4%BB%B6/1.1%E5%88%9B%E5%BB%BA%E7%9B%AE%E5%BD%95/"
  },
  {
    name: "v-fdff118e",
    path: "/documentation/congfiguration/%E5%88%9B%E5%BB%BA%E8%87%AA%E5%AE%9A%E4%B9%89g2Plots%E7%BB%84%E4%BB%B6/1.2%E9%85%8D%E7%BD%AE%E7%BB%84%E4%BB%B6/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-fdff118e").then(next)
    },
  },
  {
    path: "/documentation/congfiguration/创建自定义g2Plots组件/1.2配置组件/",
    redirect: "/documentation/congfiguration/%E5%88%9B%E5%BB%BA%E8%87%AA%E5%AE%9A%E4%B9%89g2Plots%E7%BB%84%E4%BB%B6/1.2%E9%85%8D%E7%BD%AE%E7%BB%84%E4%BB%B6/"
  },
  {
    path: "/documentation/congfiguration/%E5%88%9B%E5%BB%BA%E8%87%AA%E5%AE%9A%E4%B9%89g2Plots%E7%BB%84%E4%BB%B6/1.2%E9%85%8D%E7%BD%AE%E7%BB%84%E4%BB%B6/index.html",
    redirect: "/documentation/congfiguration/%E5%88%9B%E5%BB%BA%E8%87%AA%E5%AE%9A%E4%B9%89g2Plots%E7%BB%84%E4%BB%B6/1.2%E9%85%8D%E7%BD%AE%E7%BB%84%E4%BB%B6/"
  },
  {
    path: "/documentation/congfiguration/创建自定义g2Plots组件/1.2配置组件/",
    redirect: "/documentation/congfiguration/%E5%88%9B%E5%BB%BA%E8%87%AA%E5%AE%9A%E4%B9%89g2Plots%E7%BB%84%E4%BB%B6/1.2%E9%85%8D%E7%BD%AE%E7%BB%84%E4%BB%B6/"
  },
  {
    name: "v-89f8d372",
    path: "/documentation/congfiguration/%E5%88%9B%E5%BB%BA%E8%87%AA%E5%AE%9A%E4%B9%89g2Plots%E7%BB%84%E4%BB%B6/1.3%E6%B3%A8%E5%86%8C%E7%BB%84%E4%BB%B6/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-89f8d372").then(next)
    },
  },
  {
    path: "/documentation/congfiguration/创建自定义g2Plots组件/1.3注册组件/",
    redirect: "/documentation/congfiguration/%E5%88%9B%E5%BB%BA%E8%87%AA%E5%AE%9A%E4%B9%89g2Plots%E7%BB%84%E4%BB%B6/1.3%E6%B3%A8%E5%86%8C%E7%BB%84%E4%BB%B6/"
  },
  {
    path: "/documentation/congfiguration/%E5%88%9B%E5%BB%BA%E8%87%AA%E5%AE%9A%E4%B9%89g2Plots%E7%BB%84%E4%BB%B6/1.3%E6%B3%A8%E5%86%8C%E7%BB%84%E4%BB%B6/index.html",
    redirect: "/documentation/congfiguration/%E5%88%9B%E5%BB%BA%E8%87%AA%E5%AE%9A%E4%B9%89g2Plots%E7%BB%84%E4%BB%B6/1.3%E6%B3%A8%E5%86%8C%E7%BB%84%E4%BB%B6/"
  },
  {
    path: "/documentation/congfiguration/创建自定义g2Plots组件/1.3注册组件/",
    redirect: "/documentation/congfiguration/%E5%88%9B%E5%BB%BA%E8%87%AA%E5%AE%9A%E4%B9%89g2Plots%E7%BB%84%E4%BB%B6/1.3%E6%B3%A8%E5%86%8C%E7%BB%84%E4%BB%B6/"
  },
  {
    name: "v-81b7d7f6",
    path: "/documentation/congfiguration/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-81b7d7f6").then(next)
    },
  },
  {
    path: "/documentation/congfiguration/index.html",
    redirect: "/documentation/congfiguration/"
  },
  {
    name: "v-1cbddf19",
    path: "/documentation/congfiguration/%E5%88%9B%E5%BB%BA%E8%87%AA%E5%AE%9A%E4%B9%89g2Plots%E7%BB%84%E4%BB%B6/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1cbddf19").then(next)
    },
  },
  {
    path: "/documentation/congfiguration/创建自定义g2Plots组件/",
    redirect: "/documentation/congfiguration/%E5%88%9B%E5%BB%BA%E8%87%AA%E5%AE%9A%E4%B9%89g2Plots%E7%BB%84%E4%BB%B6/"
  },
  {
    path: "/documentation/congfiguration/%E5%88%9B%E5%BB%BA%E8%87%AA%E5%AE%9A%E4%B9%89g2Plots%E7%BB%84%E4%BB%B6/index.html",
    redirect: "/documentation/congfiguration/%E5%88%9B%E5%BB%BA%E8%87%AA%E5%AE%9A%E4%B9%89g2Plots%E7%BB%84%E4%BB%B6/"
  },
  {
    path: "/documentation/congfiguration/创建自定义g2Plots组件/",
    redirect: "/documentation/congfiguration/%E5%88%9B%E5%BB%BA%E8%87%AA%E5%AE%9A%E4%B9%89g2Plots%E7%BB%84%E4%BB%B6/"
  },
  {
    name: "v-0286bced",
    path: "/documentation/dataSource/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0286bced").then(next)
    },
  },
  {
    path: "/documentation/dataSource/index.html",
    redirect: "/documentation/dataSource/"
  },
  {
    name: "v-e14c6272",
    path: "/documentation/dataflow/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e14c6272").then(next)
    },
  },
  {
    path: "/documentation/dataflow/index.html",
    redirect: "/documentation/dataflow/"
  },
  {
    name: "v-8c956032",
    path: "/documentation/congfiguration/%E5%88%9B%E5%BB%BA%E8%87%AA%E5%AE%9A%E4%B9%89g2Plots%E7%BB%84%E4%BB%B6/1.4%E6%95%88%E6%9E%9C%E5%9B%BE/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8c956032").then(next)
    },
  },
  {
    path: "/documentation/congfiguration/创建自定义g2Plots组件/1.4效果图/",
    redirect: "/documentation/congfiguration/%E5%88%9B%E5%BB%BA%E8%87%AA%E5%AE%9A%E4%B9%89g2Plots%E7%BB%84%E4%BB%B6/1.4%E6%95%88%E6%9E%9C%E5%9B%BE/"
  },
  {
    path: "/documentation/congfiguration/%E5%88%9B%E5%BB%BA%E8%87%AA%E5%AE%9A%E4%B9%89g2Plots%E7%BB%84%E4%BB%B6/1.4%E6%95%88%E6%9E%9C%E5%9B%BE/index.html",
    redirect: "/documentation/congfiguration/%E5%88%9B%E5%BB%BA%E8%87%AA%E5%AE%9A%E4%B9%89g2Plots%E7%BB%84%E4%BB%B6/1.4%E6%95%88%E6%9E%9C%E5%9B%BE/"
  },
  {
    path: "/documentation/congfiguration/创建自定义g2Plots组件/1.4效果图/",
    redirect: "/documentation/congfiguration/%E5%88%9B%E5%BB%BA%E8%87%AA%E5%AE%9A%E4%B9%89g2Plots%E7%BB%84%E4%BB%B6/1.4%E6%95%88%E6%9E%9C%E5%9B%BE/"
  },
  {
    name: "v-f25d6e66",
    path: "/documentation/quickStart/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f25d6e66").then(next)
    },
  },
  {
    path: "/documentation/quickStart/index.html",
    redirect: "/documentation/quickStart/"
  },
  {
    name: "v-77356e2e",
    path: "/documentation/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-77356e2e").then(next)
    },
  },
  {
    path: "/documentation/index.html",
    redirect: "/documentation/"
  },
  {
    name: "v-487df90c",
    path: "/introduction/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-487df90c").then(next)
    },
  },
  {
    path: "/introduction/index.html",
    redirect: "/introduction/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]