/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Siwu-IoT-View",
  "description": "个人Siwu-IoT-View站点",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/images/logo.png"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "images/logo.png",
        "heroText": "Siwu-IoT-View",
        "tagline": "基于RuoYi-Vue 3.8.8和Dataroom 2.0 集成开发",
        "actionText": "快速上手 →",
        "actionLink": "/introduction/",
        "features": [
          {
            "title": "设计器",
            "details": "基于SpringBoot、MyBatisPlus、ElementUI、G2Plot、Echarts等技术栈的大屏设计器，具备大屏分组管理、大屏设计、大屏预览能力。"
          },
          {
            "title": "组件库",
            "details": "平台提供丰富的业务组件和数据接入能力，包括图表40 、通用组件20 、素材图片300 、自定义组件。"
          },
          {
            "title": "数据源",
            "details": "支持MySQL、Oracle、PostgreSQL、JSON等数据集接入，对于复杂数据处理还可以使用Groovy脚本数据集，使用简单，完全免费，代码开源。"
          }
        ],
        "footer": "2024 | Maked BY Su.Guichuan"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-3b2ca959",
      "path": "/",
      "lastUpdated": "11/27/2024, 9:25:45 AM",
      "lastUpdatedTimestamp": 1732670745000
    },
    {
      "frontmatter": {},
      "regularPath": "/about/",
      "relativePath": "about/index.md",
      "key": "v-5edeba8e",
      "path": "/about/",
      "lastUpdated": "11/27/2024, 9:25:45 AM",
      "lastUpdatedTimestamp": 1732670745000
    },
    {
      "title": "1.2. 配置散点图.js",
      "frontmatter": {},
      "regularPath": "/documentation/congfiguration/%E5%88%9B%E5%BB%BA%E8%87%AA%E5%AE%9A%E4%B9%89g2Plots%E7%BB%84%E4%BB%B6/1.2%E9%85%8D%E7%BD%AE%E7%BB%84%E4%BB%B6/",
      "relativePath": "documentation/congfiguration/创建自定义g2Plots组件/1.2配置组件/index.md",
      "key": "v-fdff118e",
      "path": "/documentation/congfiguration/%E5%88%9B%E5%BB%BA%E8%87%AA%E5%AE%9A%E4%B9%89g2Plots%E7%BB%84%E4%BB%B6/1.2%E9%85%8D%E7%BD%AE%E7%BB%84%E4%BB%B6/",
      "headers": [
        {
          "level": 2,
          "title": "1.2.1. 基本配置格式",
          "slug": "_1-2-1-基本配置格式"
        },
        {
          "level": 2,
          "title": "1.2.2.  version",
          "slug": "_1-2-2-version"
        },
        {
          "level": 2,
          "title": "1.2.3. category",
          "slug": "_1-2-3-category"
        },
        {
          "level": 2,
          "title": "1.2.4. title",
          "slug": "_1-2-4-title"
        },
        {
          "level": 2,
          "title": "1.2.5. chartType",
          "slug": "_1-2-5-charttype"
        },
        {
          "level": 2,
          "title": "1.2.6. name",
          "slug": "_1-2-6-name"
        },
        {
          "level": 2,
          "title": "1.2.7. setting",
          "slug": "_1-2-7-setting"
        },
        {
          "level": 2,
          "title": "1.2.7.1. 配置项中的属性说明：",
          "slug": "_1-2-7-1-配置项中的属性说明"
        },
        {
          "level": 2,
          "title": "1.2.7.3. groupName可选值",
          "slug": "_1-2-7-3-groupname可选值"
        },
        {
          "level": 2,
          "title": "1.2.8. optionHandler",
          "slug": "_1-2-8-optionhandler"
        },
        {
          "level": 2,
          "title": "1.2.9. dataHandler",
          "slug": "_1-2-9-datahandler"
        },
        {
          "level": 2,
          "title": "1.2.10. option",
          "slug": "_1-2-10-option"
        }
      ],
      "lastUpdated": "11/27/2024, 9:25:45 AM",
      "lastUpdatedTimestamp": 1732670745000
    },
    {
      "title": "1.3 注册自定义组件配置",
      "frontmatter": {},
      "regularPath": "/documentation/congfiguration/%E5%88%9B%E5%BB%BA%E8%87%AA%E5%AE%9A%E4%B9%89g2Plots%E7%BB%84%E4%BB%B6/1.3%E6%B3%A8%E5%86%8C%E7%BB%84%E4%BB%B6/",
      "relativePath": "documentation/congfiguration/创建自定义g2Plots组件/1.3注册组件/index.md",
      "key": "v-89f8d372",
      "path": "/documentation/congfiguration/%E5%88%9B%E5%BB%BA%E8%87%AA%E5%AE%9A%E4%B9%89g2Plots%E7%BB%84%E4%BB%B6/1.3%E6%B3%A8%E5%86%8C%E7%BB%84%E4%BB%B6/",
      "lastUpdated": "11/27/2024, 9:25:45 AM",
      "lastUpdatedTimestamp": 1732670745000
    },
    {
      "title": "组件库",
      "frontmatter": {},
      "regularPath": "/documentation/congfiguration/",
      "relativePath": "documentation/congfiguration/index.md",
      "key": "v-81b7d7f6",
      "path": "/documentation/congfiguration/",
      "lastUpdated": "11/27/2024, 9:25:45 AM",
      "lastUpdatedTimestamp": 1732670745000
    },
    {
      "title": "1.4效果图",
      "frontmatter": {},
      "regularPath": "/documentation/congfiguration/%E5%88%9B%E5%BB%BA%E8%87%AA%E5%AE%9A%E4%B9%89g2Plots%E7%BB%84%E4%BB%B6/1.4%E6%95%88%E6%9E%9C%E5%9B%BE/",
      "relativePath": "documentation/congfiguration/创建自定义g2Plots组件/1.4效果图/index.md",
      "key": "v-8c956032",
      "path": "/documentation/congfiguration/%E5%88%9B%E5%BB%BA%E8%87%AA%E5%AE%9A%E4%B9%89g2Plots%E7%BB%84%E4%BB%B6/1.4%E6%95%88%E6%9E%9C%E5%9B%BE/",
      "headers": [
        {
          "level": 2,
          "title": "1.4效果图",
          "slug": "_1-4效果图"
        }
      ],
      "lastUpdated": "11/27/2024, 9:25:45 AM",
      "lastUpdatedTimestamp": 1732670745000
    },
    {
      "title": "自定义g2plots组件",
      "frontmatter": {},
      "regularPath": "/documentation/congfiguration/%E5%88%9B%E5%BB%BA%E8%87%AA%E5%AE%9A%E4%B9%89g2Plots%E7%BB%84%E4%BB%B6/1.1%E5%88%9B%E5%BB%BA%E7%9B%AE%E5%BD%95/",
      "relativePath": "documentation/congfiguration/创建自定义g2Plots组件/1.1创建目录/index.md",
      "key": "v-17487942",
      "path": "/documentation/congfiguration/%E5%88%9B%E5%BB%BA%E8%87%AA%E5%AE%9A%E4%B9%89g2Plots%E7%BB%84%E4%BB%B6/1.1%E5%88%9B%E5%BB%BA%E7%9B%AE%E5%BD%95/",
      "headers": [
        {
          "level": 2,
          "title": "1.1 logos",
          "slug": "_1-1-logos"
        },
        {
          "level": 2,
          "title": "1.2. exports.js",
          "slug": "_1-2-exports-js"
        }
      ],
      "lastUpdated": "11/27/2024, 9:25:45 AM",
      "lastUpdatedTimestamp": 1732670745000
    },
    {
      "frontmatter": {},
      "regularPath": "/documentation/dataSource/",
      "relativePath": "documentation/dataSource/index.md",
      "key": "v-0286bced",
      "path": "/documentation/dataSource/",
      "lastUpdated": "11/27/2024, 9:25:45 AM",
      "lastUpdatedTimestamp": 1732670745000
    },
    {
      "title": "组件库",
      "frontmatter": {},
      "regularPath": "/documentation/congfiguration/%E5%88%9B%E5%BB%BA%E8%87%AA%E5%AE%9A%E4%B9%89g2Plots%E7%BB%84%E4%BB%B6/",
      "relativePath": "documentation/congfiguration/创建自定义g2Plots组件/index.md",
      "key": "v-1cbddf19",
      "path": "/documentation/congfiguration/%E5%88%9B%E5%BB%BA%E8%87%AA%E5%AE%9A%E4%B9%89g2Plots%E7%BB%84%E4%BB%B6/",
      "lastUpdated": "11/27/2024, 9:25:45 AM",
      "lastUpdatedTimestamp": 1732670745000
    },
    {
      "frontmatter": {},
      "regularPath": "/documentation/dataflow/",
      "relativePath": "documentation/dataflow/index.md",
      "key": "v-e14c6272",
      "path": "/documentation/dataflow/",
      "lastUpdated": "11/27/2024, 9:25:45 AM",
      "lastUpdatedTimestamp": 1732670745000
    },
    {
      "title": "项目简介",
      "frontmatter": {},
      "regularPath": "/documentation/bigScreen/",
      "relativePath": "documentation/bigScreen/index.md",
      "key": "v-0a7ee641",
      "path": "/documentation/bigScreen/",
      "headers": [
        {
          "level": 2,
          "title": "项目简介",
          "slug": "项目简介"
        },
        {
          "level": 2,
          "title": "需求分析",
          "slug": "需求分析"
        },
        {
          "level": 2,
          "title": "数据准备",
          "slug": "数据准备"
        },
        {
          "level": 2,
          "title": "选择数据",
          "slug": "选择数据"
        },
        {
          "level": 2,
          "title": "选择图表",
          "slug": "选择图表"
        },
        {
          "level": 2,
          "title": "选择数据",
          "slug": "选择数据-2"
        },
        {
          "level": 2,
          "title": "预览大屏",
          "slug": "预览大屏"
        }
      ],
      "lastUpdated": "11/27/2024, 9:25:45 AM",
      "lastUpdatedTimestamp": 1732670745000
    },
    {
      "frontmatter": {},
      "regularPath": "/introduction/",
      "relativePath": "introduction/index.md",
      "key": "v-487df90c",
      "path": "/introduction/",
      "headers": [
        {
          "level": 2,
          "title": "🎉 特别鸣谢：",
          "slug": "🎉-特别鸣谢"
        },
        {
          "level": 2,
          "title": "⭐️ 项目介绍",
          "slug": "⭐️-项目介绍"
        },
        {
          "level": 2,
          "title": "✨ 在线体验",
          "slug": "✨-在线体验"
        },
        {
          "level": 2,
          "title": "⚡ 主要功能",
          "slug": "⚡-主要功能"
        },
        {
          "level": 2,
          "title": "☝️ 技术栈",
          "slug": "☝️-技术栈"
        },
        {
          "level": 2,
          "title": "‍✈️ 系统特性",
          "slug": "‍✈️-系统特性"
        },
        {
          "level": 2,
          "title": "☘️ 演示图",
          "slug": "☘️-演示图"
        },
        {
          "level": 2,
          "title": "⛳️ 联系方式（微信：Jonehoo）",
          "slug": "⛳️-联系方式-微信-jonehoo"
        }
      ],
      "lastUpdated": "12/18/2024, 11:20:44 AM",
      "lastUpdatedTimestamp": 1734492044000
    },
    {
      "frontmatter": {},
      "regularPath": "/documentation/",
      "relativePath": "documentation/index.md",
      "key": "v-77356e2e",
      "path": "/documentation/",
      "lastUpdated": "11/27/2024, 9:25:45 AM",
      "lastUpdatedTimestamp": 1732670745000
    },
    {
      "title": "环境部署",
      "frontmatter": {},
      "regularPath": "/documentation/quickStart/",
      "relativePath": "documentation/quickStart/index.md",
      "key": "v-f25d6e66",
      "path": "/documentation/quickStart/",
      "headers": [
        {
          "level": 2,
          "title": "准备工作",
          "slug": "准备工作"
        },
        {
          "level": 2,
          "title": "运行系统",
          "slug": "运行系统"
        },
        {
          "level": 2,
          "title": "后端运行",
          "slug": "后端运行"
        },
        {
          "level": 3,
          "title": "详细步骤：",
          "slug": "详细步骤"
        },
        {
          "level": 2,
          "title": "前端运行",
          "slug": "前端运行"
        },
        {
          "level": 2,
          "title": "必要配置",
          "slug": "必要配置"
        },
        {
          "level": 2,
          "title": "部署系统",
          "slug": "部署系统"
        },
        {
          "level": 2,
          "title": "后端部署",
          "slug": "后端部署"
        },
        {
          "level": 2,
          "title": "前端部署",
          "slug": "前端部署"
        }
      ],
      "lastUpdated": "11/27/2024, 9:25:45 AM",
      "lastUpdatedTimestamp": 1732670745000
    }
  ],
  "themeConfig": {
    "logo": "/images/logo.png",
    "darkMode": true,
    "sidebar": [
      {
        "title": "介绍",
        "path": "/introduction/",
        "collapsable": false
      },
      {
        "title": "文档",
        "path": "/documentation/",
        "collapsable": false,
        "children": [
          {
            "title": "快速开始",
            "path": "/documentation/quickStart/"
          },
          {
            "title": "大屏设计器",
            "path": "/documentation/bigScreen/"
          },
          {
            "title": "组件库配置",
            "path": "/documentation/congfiguration/",
            "children": [
              {
                "title": "创建自定义g2Plots组件",
                "path": "/documentation/congfiguration/创建自定义g2Plots组件/",
                "children": [
                  {
                    "title": "1.1创建目录",
                    "path": "/documentation/congfiguration/创建自定义g2Plots组件/1.1创建目录/"
                  },
                  {
                    "title": "1.2配置组件",
                    "path": "/documentation/congfiguration/创建自定义g2Plots组件/1.2配置组件/"
                  },
                  {
                    "title": "1.3注册自定义组件",
                    "path": "/documentation/congfiguration/创建自定义g2Plots组件/1.3注册组件/"
                  },
                  {
                    "title": "1.4效果图",
                    "path": "/documentation/congfiguration/创建自定义g2Plots组件/1.4效果图/"
                  }
                ]
              }
            ]
          },
          {
            "title": "数据源配置",
            "path": "/documentation/dataSource/"
          },
          {
            "title": "数据集配置",
            "path": "/documentation/dataflow/"
          }
        ]
      },
      {
        "title": "关于",
        "path": "/about/",
        "collapsable": false
      }
    ],
    "nav": [
      {
        "text": "首页",
        "link": "/",
        "icon": "home"
      },
      {
        "text": "文档",
        "link": "/introduction/",
        "icon": "book"
      },
      {
        "text": "关于",
        "link": "/about/",
        "icon": "info-circle"
      },
      {
        "text": "在线体验",
        "link": "https://sv.jinhuwl.top:5743/",
        "icon": "info-circle"
      },
      {
        "text": "Gitee",
        "link": "https://gitee.com/jonehoo/Siwu-IoT-Views",
        "icon": "info-circle"
      }
    ],
    "lastUpdated": "上次更新",
    "repo": "https://github.com/jonehoo/Siwu-IoT-Views",
    "repoLabel": "GitHub",
    "docsDir": "docs",
    "docsBranch": "docs",
    "editLinks": false,
    "editLinkText": "帮助我们改善此页面！"
  }
}